import { CalendarDays, Clock3, Tag, UserRound, X } from 'lucide-react'
import { useShallow } from 'zustand/react/shallow'
import { getCurrentMap, useRoadmapStore, type NodePriority, type NodeStatus } from '../store/useRoadmapStore'

export function PlanningPanel() {
  const selectedId = useRoadmapStore((state) => state.selectedNodeId)
  const node = useRoadmapStore(useShallow((state) => getCurrentMap(state).nodes.find((item) => item.id === selectedId)))
  const updateNode = useRoadmapStore((state) => state.updateNode)
  const selectNode = useRoadmapStore((state) => state.selectNode)
  const toHours = (minutes?: number) => minutes ? String(minutes / 60) : ''
  const toMinutes = (value: string) => { const parsed = Number(value); return Number.isFinite(parsed) && parsed > 0 ? Math.round(parsed * 60) : undefined }
  if (!node) return null
  return <aside className="planning-panel" aria-label="Planning details"><div className="planning-panel-head"><div><span className="eyebrow">Planning</span><h2>{node.data.title}</h2></div><button className="icon-button" onClick={() => selectNode(null)} aria-label="Close planning details"><X size={16} /></button></div><label className="planning-field"><span>Status</span><select value={node.data.status} onChange={(event) => updateNode(node.id, { status: event.target.value as NodeStatus })}><option value="not-started">Not started</option><option value="in-progress">In progress</option><option value="done">Done</option></select></label><label className="planning-field"><span>Priority</span><select value={node.data.priority ?? 'medium'} onChange={(event) => updateNode(node.id, { priority: event.target.value as NodePriority })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label className="planning-field"><span><CalendarDays size={13} /> Due date</span><input type="date" value={node.data.dueDate ?? ''} onChange={(event) => updateNode(node.id, { dueDate: event.target.value || undefined })} /></label><label className="planning-field"><span><Clock3 size={13} /> Estimate hours</span><input type="number" min="0" step="0.5" value={toHours(node.data.estimatedMinutes)} onChange={(event) => updateNode(node.id, { estimatedMinutes: toMinutes(event.target.value) })} /></label><label className="planning-field"><span><Clock3 size={13} /> Actual hours</span><input type="number" min="0" step="0.5" value={toHours(node.data.actualMinutes)} onChange={(event) => updateNode(node.id, { actualMinutes: toMinutes(event.target.value) })} /></label><label className="planning-field"><span><UserRound size={13} /> Owner</span><input placeholder="Unassigned" value={node.data.owner ?? ''} onChange={(event) => updateNode(node.id, { owner: event.target.value || undefined })} /></label><label className="planning-field"><span><Tag size={13} /> Tags</span><input placeholder="design, v1" value={(node.data.tags ?? []).join(', ')} onChange={(event) => updateNode(node.id, { tags: event.target.value.split(',').map((tag) => tag.trim()).filter(Boolean) })} /></label></aside>
}
